"""Retrospective truth evaluator only after inference freeze, no estimator feedback."""
from hla_sp1_core import *
import itertools

def main():
 f=read(OUT/'INFERENCE_FREEZE.json');assert sha(OUT/'INFERENCE_RESULTS_NO_TRUTH.csv')==f['results_sha256'];dump(OUT/'EVALUATION_STARTED.json',{'time_utc':stamp(),'inference_freeze_sha256':sha(OUT/'INFERENCE_FREEZE.json')});private={r['record_id']:r for r in read(LOCAL/'test/PRIVATE_MANIFEST.json')['records']};raw=rows(OUT/'INFERENCE_RESULTS_NO_TRUTH.csv');y=np.load(LOCAL/'test/RECEIVER_DFT.npy',mmap_mode='r');recordindex={r['record_id']:i for i,r in enumerate(rows(LOCAL/'test/PUBLIC_RECORD_INDEX.csv'))};result=[];continuous=[];snrs=[]
 states=np.array([[r['truth_r_km'],r['truth_theta_deg'],r['truth_z_m']] for r in private.values()]);h=Provider(160001).field(states,exact=True)
 for step in [.10,.05]:
  rs,ths,cat=catalogue(step)
  for mesh in [160001,80001]:
   scorefile=np.load(LOCAL/f'SCORES_step{step:.2f}_n{mesh}.npy',mmap_mode='r');support=np.load(OUT/f'FULL_RANGE_SUPPORT_{step:.2f}_n{mesh}.npz');pack=support['packed_acceptance']
   for r in raw:
    if float(r['grid_step_km'])!=step or int(r['modal_mesh'])!=mesh:continue
    p=private[r['record_id']];i=recordindex[r['record_id']];method=int(r['method'][1]);ir=nearest(rs,p['truth_r_km']);it=nearest(ths,abs(p['truth_theta_deg']));iz=nearest(ZS,p['truth_z_m']);acc=np.unpackbits(pack[i,method],count=len(cat)).reshape(len(rs),len(ths),len(ZS));cell=json.loads(r['range_intervals_km']);valid=r['effective_output']=='True';labels=json.loads(r['range_labels']);joint=bool(acc[ir,it,iz]);horizontal=bool(acc[ir,it,:].any());rangeonly=any(lo<=p['truth_r_km']<=hi for lo,hi in cell);point=abs(float(r['best_r_km'])-p['truth_r_km']) if valid else float('inf');worst=max(abs(x-p['truth_r_km']) for x in labels) if valid else float('inf');cellworst=max(abs(x-p['truth_r_km']) for pair in cell for x in pair) if valid else float('inf');cscore=float(score(h[i],y[i],method));result.append(dict(r,geometry=p['geometry'],replicate=p['replicate'],truth_r_km=p['truth_r_km'],horizontal_label_retained=horizontal,joint_z_label_retained=joint,distance_cell_retained=rangeonly,continuous_truth_score=cscore,continuous_truth_score_at_or_above_threshold=cscore>=1-float(r['tau']),top1_abs_distance_error_km=point,full_label_worst_error_km=worst,full_cell_worst_error_km=cellworst))
   del scorefile,pack,support
 table(OUT/'RANGE_RESULTS_BY_RECORD.csv',result)
 for p in private.values():
  for line,snr in enumerate(p['actual_SNR_by_line_dB']):snrs.append(dict(record_id=p['record_id'],geometry=p['geometry'],replicate=p['replicate'],frequency_hz=FREQ[line],actual_receive_SNR_dB=snr,reference_only=True))
 table(OUT/'ACTUAL_RECEIVE_SNR_AND_WEAK_FIELD.csv',snrs);summary=[]
 for method,c,snr,step,mesh,g in itertools.product(['P0','P1','P2'],['C0','C1'],[20,5],[.10,.05],[160001,80001],range(8)):
  a=[r for r in result if r['method']==method and r['C']==c and int(r['reference_SNR_dB'])==snr and float(r['grid_step_km'])==step and int(r['modal_mesh'])==mesh and int(r['geometry'])==g];assert len(a)==16
  widths=np.array([float(r['envelope_width_km']) if r['effective_output']=='True' else np.inf for r in a]);err=np.array([float(r['top1_abs_distance_error_km']) for r in a]);worst=np.array([float(r['full_cell_worst_error_km']) for r in a]);valid=sum(r['effective_output']=='True' for r in a)
  summary.append(dict(method=method,C=c,reference_SNR_dB=snr,grid_step_km=step,modal_mesh=mesh,geometry=g,records=len(a),numerical_valid=16,effective_outputs=valid,empty_count=16-valid,horizontal_label_retention=sum(r['horizontal_label_retained'] for r in a)/16,joint_z_label_retention=sum(r['joint_z_label_retained'] for r in a)/16,distance_cell_retention=sum(r['distance_cell_retained'] for r in a)/16,median_envelope_km=float(np.median(widths)),P90_envelope_km=float(np.quantile(widths,.9,method='higher')),max_envelope_km=float(widths.max()),median_point_error_km=float(np.median(err)),P90_point_error_km=float(np.quantile(err,.9,method='higher')),max_point_error_km=float(err.max()),median_full_cell_worst_error_km=float(np.median(worst)),max_full_cell_worst_error_km=float(worst.max()),multibranch_count=sum(int(r['interval_count'])>1 for r in a),full_domain_width_count=sum(r['effective_output']=='True' and float(r['envelope_width_km'])>=14.9 for r in a),median_occupied_length_km=float(np.median([float(r['occupied_cell_length_km']) for r in a if r['effective_output']=='True'])) if valid else 'EMPTY_NOT_ZERO',meets_signal=valid>=15 and sum(r['horizontal_label_retained'] for r in a)>=15 and np.median(widths)<=10))
 table(OUT/'RANGE_RESULTS_BY_GEOMETRY.csv',summary);comparison=[]
 for method,c,snr in itertools.product(['P0','P1','P2'],['C0','C1'],[20,5]):
  a=[r for r in summary if r['method']==method and r['C']==c and r['reference_SNR_dB']==snr and r['grid_step_km']==.05 and r['modal_mesh']==160001];comparison.append(dict(method=method,C=c,reference_SNR_dB=snr,records=sum(r['records'] for r in a),effective_outputs=sum(r['effective_outputs'] for r in a),horizontal_label_retention=float(np.mean([r['horizontal_label_retention'] for r in a])),joint_z_label_retention=float(np.mean([r['joint_z_label_retention'] for r in a])),distance_cell_retention=float(np.mean([r['distance_cell_retention'] for r in a])),median_geometry_envelope_km=float(np.median([r['median_envelope_km'] for r in a])),median_geometry_point_error_km=float(np.median([r['median_point_error_km'] for r in a])),maximum_cell_worst_error_km=max(r['max_full_cell_worst_error_km'] for r in a),geometries_meeting_signal=sum(r['meets_signal'] for r in a)))
 table(OUT/'METHOD_AND_CALIBRATION_COMPARISON.csv',comparison);grid=[];by={(r['record_id'],r['method'],float(r['grid_step_km']),int(r['modal_mesh'])):r for r in result}
 for r in result:
  if float(r['grid_step_km'])!=.05 or int(r['modal_mesh'])!=160001:continue
  coarse=by[(r['record_id'],r['method'],.10,160001)];low=by[(r['record_id'],r['method'],.05,80001)];grid.append(dict(record_id=r['record_id'],method=r['method'],C=r['C'],SNR=r['reference_SNR_dB'],fine_minus_main_point_km=float(r['best_r_km'])-float(coarse['best_r_km']),fine_minus_main_width_km=float(r['envelope_width_km'])-float(coarse['envelope_width_km']) if r['effective_output']=='True' and coarse['effective_output']=='True' else 'UNRESOLVED_EMPTY',grid_horizontal_retention_flip=r['horizontal_label_retained']!=coarse['horizontal_label_retained'],modal_point_difference_km=float(r['best_r_km'])-float(low['best_r_km']),modal_width_difference_km=float(r['envelope_width_km'])-float(low['envelope_width_km']) if r['effective_output']=='True' and low['effective_output']=='True' else 'UNRESOLVED_EMPTY',modal_horizontal_retention_flip=r['horizontal_label_retained']!=low['horizontal_label_retained']))
 table(OUT/'GRID_AND_NUMERIC_SENSITIVITY.csv',grid);print('EVALUATION COMPLETE',len(result),flush=True)
if __name__=='__main__':main()
