from hla_sp1_core import *
import subprocess,ast,shutil

def main():
 assert read(OUT/'PREFLIGHT.json')['PASS']
 assert subprocess.check_output(['git','rev-parse','HEAD'],text=True).strip()==PARENT
 required=['results/R4_SINGLE_HLA_CARRIER_REFERENCE_CONTRAST_PILOT/GPT_SYNC.md','results/R4_SINGLE_HLA_CARRIER_REFERENCE_CONTRAST_PILOT/DECISION.json','results/R4_SINGLE_HLA_RADIAL_RECEIVER_EXTRACTION_PILOT/GPT_SYNC.md','results/R4_SINGLE_HLA_RADIAL_RECEIVER_EXTRACTION_PILOT/DECISION.json','results/R4_SINGLE_HLA_RADIAL_INCREMENT_PRECISION_PILOT/FOUR_PARAMETER_RESULTS.md','results/R4_SINGLE_HLA_SOURCE_PROFILED_HORIZONTAL_PILOT/OFFGRID_TRUTH_EVALUATION_ONLY.csv','results/R4_E2_G0_HLA_DIFFERENCE_INFORMATION/GPT_SYNC.md','results/R4_E2_G0_HLA_DIFFERENCE_INFORMATION/E2_IMPLEMENTATION_CONTRACT.md','results/R4_E2_G0_HLA_DIFFERENCE_INFORMATION/E2_HLA_PRIMARY_PAPER_COMPARISON.md','results/R4_E2_NINE_PAIR_INFORMATION_PILOT/PILOT_REPORT.md','results/R4_OBSERVABILITY_FRONTIER_RESEARCH_RESET/LITERATURE_IMPLEMENTATION_COVERAGE.csv','hla_h1_core.py','results/R3_C2_Yang_SA_depth/R3_C2_1/_kraken_zgrid/zgrid_f201.env']
 prov=[]
 for name in required:
  p=ROOT/name;b=p.read_bytes();blob=subprocess.check_output(['git','show',PARENT+':'+name]);prov.append(dict(path=name,working_sha256=sha(p),parent_git_blob_sha256=hashlib.sha256(blob).hexdigest(),working_bytes=len(b),blob_bytes=len(blob),working_CRLF=b.count(b'\r\n'),blob_CRLF=blob.count(b'\r\n')))
 table(OUT/'INPUT_PROVENANCE.csv',prov);truth=ROOT/required[5];dump(OUT/'TEST_PANEL_SOURCE_HASH.json',{'file':required[5],'sha256':sha(truth),'all_rows':8,'known_development_geometry_not_fresh_confirmation':True})
 dump(OUT/'NEW_TASK_AND_PARENT.json',{'parent':PARENT,'new_task_sha256':sha(OUT/'DELEGATED_TASK.md'),'new_stage':'HLA_SP1_STATIC_RECEIVER_SPATIAL_RANGE_PILOT','old_RX1_RX1Z_E2_not_rerun':True})
 method='''# Method identity (explicit custom comparison)

[Yin, Ko, Lee2026](https://www.mdpi.com/1424-8220/26/5/1495), DOI10.3390/s26051495: publisher XML archived at D:/ProjectStorage/WSL-CZ/e2-source-review/yin_xml.xml was read, including equations2–3 and9–12. Both data and replica use the high-frequency conjugate product; multipath cross terms remain. Their15-element VLA has70m spacing/980m aperture at195km, source1000m,250–350Hz, single-digit difference frequencies. These resources and performance do not transfer to14m HLA. We implement no MVDR/MUSIC, no bandwidth average and no low-frequency field substitution.

[Park2024](https://www.jask.or.kr/articles/xml/9Vj9/), DOI10.7776/ASK.2024.43.1.029: publisher HTML and archived prior comparison inspected. Their HLA/CZ test did not show a clear mismatch robustness advantage over MFP. Their bandwidth average, difference-frequency acoustic replica and truth-local peak selection differ from ours. Missing array specifications/printed inconsistencies in the prior audit stay unresolved.

[Geroski & Dowling2021](https://pubmed.ncbi.nlm.nih.gov/34340502/), DOI10.1121/10.0005477: original abstract only, not full implementation recovered. Phase-only autoproduct motivation is retained; P2 is solely the explicit pairwise formula in the task, not a full POMAP reproduction.

P0 is frequency/segment averaged normalized squared inner product of raw frequency vectors. P1 uses each registered high-frequency pair on both data and replica and then normalizes; three different difference frequencies are averaged only as scores. P2 normalizes each element phase then uses squared inner product/64. K=8 independent static source/noise segments is not bandwidth averaging. Unknown complex source scalars cancel from all noise-free normalized scores; noise changes SNR. For cross-frequency constant G_m, P1 cancels its phase, while P2 additionally cancels positive magnitude. C1 does not cover frequency-dependent gains/delays. This algebra is not a new invention or a noisy performance theorem.
'''
 (OUT/'METHOD_IDENTITY.md').write_text(method,encoding='utf-8')
 (OUT/'OBSERVATION_CONTRACT.md').write_text('''# Observation and permissions

Static8element HLA x=[-7,-5,-3,-1,1,3,5,7]m, z200m. Three tones201/235/283Hz exactly on2s DFT bins;fs1024,N2048,K8. Real waveform x=2Re sum_f S_fk G_m H_fm exp(i2pi f n/fs)+eta. Separate phase Uniform(-pi,pi), amplitude dB Uniform(-3,3) per frequency/segment. C1 gains amplitude dB Uniform(-1,1), phase Uniform(-30,30)degrees, fixed per record across frequency/segment. No source/gain alignment is available to receiver.

Reference power is the median across16 frozen calibration geometries of unit-source power averaged across3frequencies and8elements; exact value in PREFLIGHT.json. nu=P_ref/10^(SNR/10), shared within a reference20/5dB condition. Each real noise sample has variance N*nu. Therefore E|DFT noise coefficient|^2=(N*N*nu)/N^2=nu; real/imaginary bin variance nu/2 at these non-DC tones. Reference complex-spectrum SNR is not broadband waveform SNR or per-record actual SNR. Actual weak-field SNRs are evaluation-only, no weak-record removal.

Generator alone reads private geometry,H,S,G. It archives all innovations and writes a whitelist public index of ID,path,SHA,C,SNR,fs,N,K. Receiver reads only this and public metadata and waveform. Test inference reads receiver DFT, public index, independent frozen thresholds, and full replica catalogue. It has no private ID lookup. Evaluation opens test truth only after INFERENCE_FREEZE. Calibration alone uses its private nearest joint labels; thresholds are frozen before test generation/inference.

SeedSequence: calibration geometry2026101017; calibration receiver2026101018; test2026101019; control2026101020. Each geometry/replicate spawns independent source/noise/gain streams; C/SNR reuse innovations. The source and noise archive stays private localD. K, pairs and paired conditions are not independent geometries. Three pair features share the same DFT and algebraic cycle; no Gaussian independence model is asserted.
''',encoding='utf-8')
 (OUT/'STATIC_SCOPE_AND_TRANSFER_GAP.md').write_text('''# Scope and transfer gap

STATIC_CONTROL / FINITE_CATALOGUE / DEPTH_NOT_TARGET / NO_VELOCITY_ESTIMATE. No Doppler, group delay, target motion, frequency drift, blind line acquisition, broadband source occupancy, independent fixed-gain estimation, real-data extraction or environmental uncertainty certification. Eight independent2s segments are not a continuous16s emission with boundary transitions or a1200s motion record. Bin alignment, exact navigation and matched nominal environment are favorable controls. Original H1,H2,RX1,RX1Z,E2,H3 conclusions and R4=0 remain. CHIGH truncation remains uncertified; static grid comparisons cannot certify omitted modes. Mirrors follow the exact range-independent horizontal symmetry. Depth is searched150:5:250 and not a performance target; v/psi are NOT_EVALUATED.

Threshold nearest-rank95% is a finite empirical calibration filter, not a theoretical95% confidence set, sea-trial coverage or continuous global certificate. Full candidate labels and clipped half-grid cells are distinct; cells are sampling resolution, not conservative continuous enclosures. Empty support is EMPTY_NOT_ZERO and unconditional errorsINF. Strict score then ascending candidateID determines ties. Both grids and modal meshes remain, no truth-local refinement or threshold retuning.
''',encoding='utf-8')
 sources=sorted(ROOT.glob('hla_sp1_*.py'))
 for p in sources:ast.parse(p.read_text(encoding='utf-8-sig'))
 names=['DELEGATED_TASK.md','CALIBRATION_PANEL.csv','PREFLIGHT.json','PROVIDER_PROVENANCE.json','PRECOMPUTE_CONTRACT.json','INPUT_PROVENANCE.csv','TEST_PANEL_SOURCE_HASH.json','METHOD_IDENTITY.md','OBSERVATION_CONTRACT.md','STATIC_SCOPE_AND_TRANSFER_GAP.md','NEW_TASK_AND_PARENT.json'];pref=read(OUT/'PREFLIGHT.json')
 dump(OUT/'DESIGN_FREEZE.json',{'parent':PARENT,'time_utc':stamp(),'task_sha256':sha(OUT/'DELEGATED_TASK.md'),'code_sha256':{p.name:sha(p) for p in sources},'input_sha256':{n:sha(OUT/n) for n in names},'reference_power':pref['reference_power'],'nu':pref['nu_by_reference_SNR_dB'],'panel_sizes':{'calibration_records':1024,'test_records':512},'methods':['P0','P1_PRIMARY','P2'],'depths':ZS.tolist(),'frequencies':FREQ.tolist(),'paired_frequencies':PAIRS,'steps_km':[.10,.05],'theta_steps_deg':[.25,.125],'grids_nonnegative_counts':[66591,259161],'mirrors':'restore +/- theta exactly, not duplicate zero','modal_meshes':[160001,80001],'generation_mesh':160001,'all_returned_modes':True,'threshold':'256 D at nearest(r,abs(theta),true calibration z), nearest rank95%; ties lower numeric label; freeze before test; same tau for80001 numerical control','tie_rule':'strict score then first ascending candidateID','signal_rule':'P1 C0 20dB at least5/8 geometries >=15/16 effective and horizontal retention, median nonempty cell envelope<=10km, coarse/fine conclusion not reversed','empty_rule':'not zero width; rejected and numerical failure errors INF','numeric_rules':{'interpolation_vector_relative':1e-5,'direct_score_absolute':1e-7,'boundary_flip':'report exact and interpolated without altering tau; any flip triggers NUMERICAL_OR_GRID_LIMITED','major_numeric_change':'modal or grid method signal verdict reversed, or median abs envelope change>1km; report limited','FIELD_shape_relative':.002,'roundoff_B':1e-10},'chunk_candidates':4096,'score_storage':'localD float64; all raw strictscores retained','compute_budget':{'total_wall_s':14400,'RSS_bytes':8*1024**3,'BLAS_threads':4,'local_bytes':16*1024**3,'repo_added_bytes':256*1024**2,'single_compute_process':True,'KRAKEN_max':6,'FIELD_max':3},'stage_order':'A then calibration generation/receiver/threshold freeze; test generation/receiver/full inference/evaluation/cold audit/B/STOP','new_solver_calls_already_prepared_for_reference_power':{'KRAKEN':6,'FIELD':3},'sources':{'Yin_XML_sha256':sha('D:/ProjectStorage/WSL-CZ/e2-source-review/yin_xml.xml'),'Park_HTML_sha256':sha('D:/ProjectStorage/WSL-CZ/e2-source-review/park.html')},'R4':0})
 print('DESIGN READY',len(sources),'modules',flush=True)
if __name__=='__main__':main()
